### ISSUE TITLE
Audacious plugins qtui fails to build with QT 6.7.1

### ISSUE THREAD

**Issue by madpilot78** [audacious-media-player/audacious#1393]
**Describe the bug**
As the title says, Audacious plugin qtui fails to build with latest QT6. I'm experiencing this in FreeBSD, where, in the official ports tree, the QT libraries have recently been updated to 6.7.1

I'm getting the following build time error:

```
FAILED: src/qtui/qtui.so.p/main_window.cc.o 
c++ -Isrc/qtui/qtui.so.p -Isrc/qtui -I../src/qtui -I/usr/local/include -I/usr/local/include/qt6/QtCore -I/usr/local/include/qt6 -I/usr/local/lib/qt6/mkspecs/freebsd-clang -I/usr/local/include/qt6/QtWidgets -I/usr/local/include/qt6/QtGui -fdiagnostics-color=never -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu++17 -ffast-math -Wtype-limits -fvisibility=hidden -Wno-non-virtual-dtor -Woverloaded-virtual -include /wrkdirs/usr/ports/multimedia/audacious-plugins/work-qt6/audacious-plugins-4.4-beta1/_build/src/config.h -O2 -pipe -march=x86-64-v2 -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -DLIBICONV_PLUG -isystem /usr/local/include -fPIC -DQT_GUI_LIB -DQT_WIDGETS_LIB -DQT_CORE_LIB -MD -MQ src/qtui/qtui.so.p/main_window.cc.o -MF src/qtui/qtui.so.p/main_window.cc.o.d -o src/qtui/qtui.so.p/main_window.cc.o -c ../src/qtui/main_window.cc
In file included from ../src/qtui/main_window.cc:20:
In file included from ../src/qtui/main_window.h:26:
In file included from /usr/local/include/libaudqt/dock.h:24:
In file included from /usr/local/include/qt6/QtWidgets/QWidget:1:
In file included from /usr/local/include/qt6/QtWidgets/qwidget.h:9:
/usr/local/include/qt6/QtCore/qobject.h:160:23: error: static assertion failed due to requirement 'QtPrivate::HasQ_OBJECT_Macro<DockWidget>::Value': No Q_OBJECT in the class passed to QObject::findChildren
  160 |         static_assert(QtPrivate::HasQ_OBJECT_Macro<ObjType>::Value,
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/qt6/QtCore/qobject.h:177:16: note: in instantiation of function template specialization 'QObject::findChildren<DockWidget *>' requested here
  177 |         return findChildren<T>(QAnyStringView{}, options);
      |                ^
../src/qtui/main_window.cc:220:19: note: in instantiation of function template specialization 'QObject::findChildren<DockWidget *>' requested here
  220 |     for (auto w : findChildren<DockWidget *>())
      |                   ^
1 error generated.
```

**Steps to reproduce**
Try to build with QT libraries version 6.7.1

**Expected behavior**
Compile without errors.

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp)

Both 4.3.1 and 4.4.0-beta1

* Operating system and version

FreeBSD, any version (this is also happening on the official FreeBSD build cluster creating binary packages from ports)

Almost sure this will also affect Linux.

**Comment by radioactiveman** [comment]
Yes, Linux is also affected. I see it on Arch Linux as well which ships Qt 6.7.1 now.

@jlindgren90: Could you please take a look? I can't get it to compile.

https://doc.qt.io/qt-6/qobject.html#findChildren vs. https://doc.qt.io/archives/qt-6.0/qobject.html#findChildren
> Note: In Qt versions prior to 6.7, this function took name as QString, not QAnyStringView.

Neither `findChildren<DockWidget *>(Qt::FindChildrenRecursively)` nor
`findChildren<DockWidget *>(QAnyStringView())` work.

**Comment by jlindgren90** [comment]
Fixed with https://github.com/audacious-media-player/audacious-plugins/commit/1f0bc4c6940d27905d11e3324e30c6a63fad6392.

`QObject::findChildren` does not seem very well documented. It seems it only works with `Q_OBJECT` types, and in previous versions it would implicitly use the parent `Q_OBJECT` type if passed a subclass declared without `Q_OBJECT`. See for example: https://stackoverflow.com/questions/35869441/why-is-qobject-findchildren-returning-children-with-a-common-base-class

Now Qt developers have made this implicit fallback an error, and we have to pass a type declared with `Q_OBJECT` directly.

**Comment by jlindgren90** [comment]
Found it in the changelog: https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.7.1/release-note.md

> 9c1752d7b1 QObject: add check for Q_OBJECT macro to findChild(ren)
> The class template parameter passed to QObject::findChild() or
> findChildren() is now required to have the Q_OBJECT macro. Forgetting to
> add it could result in finding children of the nearest ancestor class
> that has the macro.
